# Build stage
FROM golang:1.23.4-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o sensor ./cmd/sensor

# Runtime stage
FROM alpine:3.20

WORKDIR /root/

COPY --from=builder /app/sensor .
COPY --from=builder /app/cfg /cfg

ENTRYPOINT ["./sensor"]
