// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.5
// source: api/teleprobe.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetrySinkService_Report_FullMethodName = "/teleprobe.api.TelemetrySinkService/Report"
)

// TelemetrySinkServiceClient is the client API for TelemetrySinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetrySinkServiceClient interface {
	Report(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type telemetrySinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetrySinkServiceClient(cc grpc.ClientConnInterface) TelemetrySinkServiceClient {
	return &telemetrySinkServiceClient{cc}
}

func (c *telemetrySinkServiceClient) Report(ctx context.Context, in *Metric, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TelemetrySinkService_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetrySinkServiceServer is the server API for TelemetrySinkService service.
// All implementations must embed UnimplementedTelemetrySinkServiceServer
// for forward compatibility.
type TelemetrySinkServiceServer interface {
	Report(context.Context, *Metric) (*emptypb.Empty, error)
	mustEmbedUnimplementedTelemetrySinkServiceServer()
}

// UnimplementedTelemetrySinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetrySinkServiceServer struct{}

func (UnimplementedTelemetrySinkServiceServer) Report(context.Context, *Metric) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedTelemetrySinkServiceServer) mustEmbedUnimplementedTelemetrySinkServiceServer() {}
func (UnimplementedTelemetrySinkServiceServer) testEmbeddedByValue()                              {}

// UnsafeTelemetrySinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetrySinkServiceServer will
// result in compilation errors.
type UnsafeTelemetrySinkServiceServer interface {
	mustEmbedUnimplementedTelemetrySinkServiceServer()
}

func RegisterTelemetrySinkServiceServer(s grpc.ServiceRegistrar, srv TelemetrySinkServiceServer) {
	// If the following call pancis, it indicates UnimplementedTelemetrySinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetrySinkService_ServiceDesc, srv)
}

func _TelemetrySinkService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetrySinkServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetrySinkService_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetrySinkServiceServer).Report(ctx, req.(*Metric))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetrySinkService_ServiceDesc is the grpc.ServiceDesc for TelemetrySinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetrySinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teleprobe.api.TelemetrySinkService",
	HandlerType: (*TelemetrySinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _TelemetrySinkService_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/teleprobe.proto",
}
