// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.5
// source: api/teleprobe.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_teleprobe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_teleprobe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_teleprobe_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_teleprobe_proto protoreflect.FileDescriptor

const file_api_teleprobe_proto_rawDesc = "" +
	"\n" +
	"\x13api/teleprobe.proto\x12\rteleprobe.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"m\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2Q\n" +
	"\x14TelemetrySinkService\x129\n" +
	"\x06Report\x12\x15.teleprobe.api.Metric\x1a\x16.google.protobuf.Empty\"\x00B\x06Z\x04api/b\x06proto3"

var (
	file_api_teleprobe_proto_rawDescOnce sync.Once
	file_api_teleprobe_proto_rawDescData []byte
)

func file_api_teleprobe_proto_rawDescGZIP() []byte {
	file_api_teleprobe_proto_rawDescOnce.Do(func() {
		file_api_teleprobe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_teleprobe_proto_rawDesc), len(file_api_teleprobe_proto_rawDesc)))
	})
	return file_api_teleprobe_proto_rawDescData
}

var file_api_teleprobe_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_teleprobe_proto_goTypes = []any{
	(*Metric)(nil),                // 0: teleprobe.api.Metric
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_api_teleprobe_proto_depIdxs = []int32{
	1, // 0: teleprobe.api.Metric.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: teleprobe.api.TelemetrySinkService.Report:input_type -> teleprobe.api.Metric
	2, // 2: teleprobe.api.TelemetrySinkService.Report:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_teleprobe_proto_init() }
func file_api_teleprobe_proto_init() {
	if File_api_teleprobe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_teleprobe_proto_rawDesc), len(file_api_teleprobe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_teleprobe_proto_goTypes,
		DependencyIndexes: file_api_teleprobe_proto_depIdxs,
		MessageInfos:      file_api_teleprobe_proto_msgTypes,
	}.Build()
	File_api_teleprobe_proto = out.File
	file_api_teleprobe_proto_goTypes = nil
	file_api_teleprobe_proto_depIdxs = nil
}
