name: Teleprobe CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download Go modules
        run: go mod download

      - name: Run tests with race and coverage
        run: |
          mkdir -p bin
          go test -v -race -coverprofile=bin/coverage.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: bin/coverage.out

  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build sensor image
        run: docker build -f Dockerfile.sensor -t teleprobe/sensor:ci .

      - name: Build sink image
        run: docker build -f Dockerfile.sink -t teleprobe/sink:ci .
